#!/bin/env bash
# this script transfers a file from our client to a server

# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Disable strict host key checking for scp
export SCP_OPTS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$4" "$1" "$3@$2":~/
