#!/usr/bin/env bash
# this bash script displays 10 times Best Scool ,
# but the 4th display bad luck , and the 8th display good luck
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((++i))
done
